[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "static"

[functions]
  included_files = ["app.py", "templates/**", "uploads/**"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/main"
  status = 200
